// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ChangeBaseMap: typeof import('./components/ChangeBaseMap/index.vue')['default']
    ChangeSource: typeof import('./components/ChangeSource/index.vue')['default']
    City: typeof import('./components/City/index.vue')['default']
    CityBlock: typeof import('./components/City/CityBlock/index.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Login: typeof import('./components/login.vue')['default']
    MapLegend: typeof import('./components/MapLegend/index.vue')['default']
    MapSearch: typeof import('./components/MapSearch/index.vue')['default']
    ReleaseChoseRange: typeof import('./components/ReleaseChoseRange/index.vue')['default']
    Releasedialog: typeof import('./components/Releasedialog/index.vue')['default']
    ReleaseStartCompile: typeof import('./components/ReleaseStartCompile/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VersionContrast: typeof import('./components/VersionContrast/index.vue')['default']
  }
}
