export default {
    misX: state => state.userInfo.username,
    chatId: state => state.chatId,
    ctiVersion: state => state.ctiVersion,
    inside: state => state.ctiVersion !== 0,
    uploadFile: state => state.uploadFile,
    uploadFileSuccess: state => state.uploadFileSuccess,
    uploadFileFail: state => state.uploadFileFail,
    uploadTicketId: state => state.uploadTicketId,
    imgUploadStatus: state => state.imgUploadStatus,
    loginType: state => state.loginType,
    isPrivateSpace: state => state.spaceDomain && state.spaceDomain !== 'ticket',
    spaceDomain: state => state.spaceDomain,
    guard: state => state.guard,
    rgPermissionMap: state => state.rgPermissionMap,
    env: state => state.env,
    nonWorking: state => state.detailPermission && state.detailPermission.isWorkHour === false,
    detailOperatePermission: state => state.detailPermission.detailOperate,
    spaceList: state => state.spaceList,
    createEntrance: state => state.createEntrance,
    createReferrer: state => state.createReferrer,
    inspectionInfo: state => state.inspectionInfo,
    language: state => state.language,
    timeZone: state => state.timeZone,
    timeZoneList: state => state.timeZoneList
};
