export const approveTableColumns = [
  { fixed: true, prop: "id", label: "id", width: "100", align: "center" },
  {
    fixed: true,
    prop: "valId",
    label: "批次id",
    width: "120",
    align: "center",
  },
  {
    fixed: true,
    prop: "businessNameCn",
    label: "场站中文名",
    width: "150",
    align: "center",
  },
  { fixed: true, prop: "mapId", label: "mapid", width: "200", align: "center" },
  {
    fixed: true,
    prop: "businessId",
    label: "业务场景id",
    width: "120",
    align: "center",
  },
  {
    fixed: true,
    prop: "autoqaConfigName",
    label: "autoQA套餐名称",
    width: "100",
    align: "center",
  },
  { prop: "materialId", label: "资料id", width: "120", align: "center" },
  { prop: "permit", label: "准出情况", width: "100", align: "center" },
  {
    prop: "autoqaValueCosUrl",
    label: "autoQA指标值详情",
    width: "100",
    align: "center",
  },
  {
    prop: "autoqaResultCosUrl",
    label: "autoQA结果详情",
    width: "100",
    align: "center",
  },
  { prop: "createTime", label: "创建时间", width: "180", align: "center" },
  { prop: "updateTime", label: "完成时间", width: "180", align: "center" },
];
